### ISSUE TITLE
Add a "Conflicting plugins" check

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Migration-Plugin#49]
See: https://docs.classicpress.net/installing-classicpress/#plugin-conflicts

Unfortunately we didn't record the slugs of these plugins, so this will take a bit of testing.

**Comment by mattyrob** [comment]
As far as I can tell from the WordPress plugin repository the plugin slugs for the 5 plugins currently listed are:
`wp-config-file-editor`
`disable-wp-core-updates-advance`
`disable-wordpress-updates`
`wp-downgrade`
`wordfence`

**Comment by TukuToi** [comment]
Adding note from Slack here.

The simplest here is to just scan the Theme declarations.
Instead of expensive scans against a hardcoded or semi-hardcoded list of themes (or functions), we can simply check the theme readme.txt file for the `Requires at least` tag.
If that is below or equal to 4.9 we are good, if not (no matter if empty, or above) we should throw a warning.

This is quick and requires no further magic than scanning the readme.txt file for the active theme.

---

About the plugins listed on https://docs.classicpress.net/installing-classicpress/#plugin-conflicts - I suggest to remove that list.

Reasons:
1. At least one of those plugins is closed due to security reason: https://es.wordpress.org/plugins/wp-config-file-editor/
2. All those plugins require WP Version _below_ 4.9, and we promise that _all_ plugins work if they specifically require a lower than or equal to 4.9 version. Thus, we need to specify that when say "these plugins have been reported not compatible" as of 
- what exactly is happening (ticket, report etc - I do not see any. Thus this is just hearsay for now)
- wether or not the report is made to plugin dev
- wether or not the issue is actually on CP side or other side

I am speaking of experience when I say that listing "incompatible" plugins openly like that you get exactly 2 things:
- problems
- scared users

That's all. No one wins or gets any wiser.
If we have tickets somewhere we can link to, then it makes already more sense, but bottom lines, there should be no such lists, because the y became unmaintainable and (as already happened here) outdated over time.

@nylen / @mattyrob  do you agree?
I will then remove the list, and keep it hidden for now.

**Comment by striebwj** [comment]
It is less that they conflict with CP itself, and more that they conflicts with the migration process. Based off that doc, unless I am missing something?

**Comment by mattyrob** [comment]
The docs website section currently starts:

"The following plugins have been reported to conflict with the ClassicPress migration plugin or with ClassicPress itself:"

We now have code in the Migration Plugin that alerts migrators to issue with plugins preventing migration.

So, my thought would be to remove reference to migration from that section - it save us from having to keep the docs and migration API updated as separate entities to reduces maintenance burden.

That would just leave a list of plugins that 'work' on ClassicPress but cannot offer a full feature set - like WordFence checksum validation for example besuace it is using the WordPress checksums rather than the ClassicPress ones.

**Comment by TukuToi** [comment]
>So, my thought would be to remove reference to migration from that section - it save us from having to keep the docs and migration API updated as separate entities to reduces maintenance burden.

Agreed, and I will do this tomorrow first thing.

**Comment by TukuToi** [comment]
As that DOC is about _installing_ CP I removed the section entirely. When read about how to install something I don't want to hear about all the issues that will happen. That is another story, like better suited for _requirements_, but for that, again, we'd need a more precise list about what actually the issues are.

The contents of said section are here for safe keeping:
```
Plugin conflicts

The following plugins have been reported to conflict with the ClassicPress migration plugin or with ClassicPress itself:

WP Config File Editor — reported to conflict with the migration process. Disable it before proceeding with the migration.
Disable WP Core Updates Advance — reported to conflict with the migration process. Disable it before proceeding with the migration.
Disable All WordPress Updates — reported to conflict with the migration process. Disable it before proceeding with the migration.
WP Downgrade | Specific Core Version — reported to conflict with the migration process. Disable it before proceeding with the migration.
Wordfence - Wordfence doesn't know how to scan ClassicPress core files for changes yet. After installing ClassicPress, uncheck this option: Scan Options → General Options → Scan core files against repository versions for changes. There will also be a few more errors if you have the Scan wp-admin and wp-includes for files not bundled with WordPress option enabled, because ClassicPress has added new files. Currently this is normal and expected.
```
