### ISSUE TITLE
Define steps required that the plugin will need to take to enable migration

### ISSUE THREAD

**Issue by scottybo** [ClassicPress/ClassicPress-Migration-Plugin#5]
Let's use this issue to spec out how this plugin will handle the transition

**Comment by nylen** [comment]
Some thoughts...

The initial migration is our first and best opportunity to drop older PHP versions and other deprecated code.

It seems like people want to bump the PHP version pretty aggressively, so I think our initial release should drop support for PHP 5.2 through 5.5.  (I think doing any more than that is not feasible until v2.0.0, due to the huge number of PHP 5.6 servers still out there.)

A lot of the WP.org API endpoints are still called via `http:` if there is no support for making **outgoing** HTTPS requests on the server (this is totally separate from serving the site itself via HTTPS).  Let's get rid of this code, it should almost never be needed anymore, and we will need to rely on secure communication for the updates (I don't think GitHub even supports downloads over HTTP).

We'll probably find other deprecated code that is fairly easy to drop too.

We can detect these conditions (old PHP version, no HTTPS request support, etc) in the migration plugin and prevent the migration.  We can also track how many people each of these checks excludes so that we know whether we need to re-evaluate.

Then, to do the migration, we need to hook into the core update routine (using filters, without modifying WP code) and make WP think an update is available, then override the update package with our zip file from GitHub.  We need at least a couple of things first:

- Better understanding of how the core update process works (cc @ginsterbusch https://github.com/ClassicPress/ClassicPress/issues/46)
- An alpha zip file or two that we can use for internal testing

We'll want to prompt users to back up their site and confirm that we've done it.  As much as we try to get it perfect, there will be some situations where this won't work.

Let's build the migration plugin with some options for "release channel" (alpha/beta/stable etc).

**Comment by nylen** [comment]
You want the `build/` directory generated by `grunt build`. There are also a bunch of minified JS and CSS files here for example.

The part I'm not sure about is whether there are any extra steps to generate a zip file.

**Comment by ginsterbusch** [comment]
@nylen: yep, possibly, but it did work perfectly well with the two steps above :)

**Comment by ginsterbusch** [comment]
BTT: I'm working on it. That is, better understanding of how the update process and the wp.org API works.

cu, w0lf.

**Comment by dsnid3r** [comment]
@ginsterbusch where are you at on this? What’s left to be done and how can other people jump in?

**Comment by nylen** [comment]
Closing, as this is mostly all implemented now:

![2018-10-22t15 12 49-05 00](https://user-images.githubusercontent.com/227022/47320911-7b3db180-d618-11e8-9848-a8a1fa81db91.png)

The only thing left is locale handling, but we'll get to that when we have locale-specific builds.

**Comment by nylen** [comment]
Locale handling: #18
