### ISSUE TITLE
Required steps for migration from WordPress to ClassicPress

### ISSUE THREAD

**Issue by ginsterbusch** [ClassicPress/ClassicPress-Migration-Plugin#6]
**Note:** This is essentially an appendix to issue #5 - and contains my findings about the WP upgrade mechanisms and possible measures to use them.

# Required steps for migration from WordPress to ClassicPress

At the current time of writing, there are several steps before AND after migrating to ClassicPress.

# Steps to do before-hand

## 1. Increase PHP version to at least 5.6
Optionally use the PHP Compatiblity Checker plugin to test if all installed plugins and the currently active theme are compatible with PHP 5.6 and upwards.

## 2. Enable SSL 
Preferably enable SSL, eg. using Let's Encrypt or a basic SSL certificate, which nowadays is usually supplied by your hosting company.
Optionally install an SSL Enforcer plugin, which should help to avoid issues with mixed content (SSL and Non-SSL).

## 3. Disable automatic updates 
Preferably disable automatic updates completely, to avoid getting accidently converted back to WordPress - in this case to a nightly build.
This is achieved by adding the following constant to the wp-config:
`define( 'AUTOMATIC_UPDATER_DISABLED', true );`

Also see: https://codex.wordpress.org/Configuring_Automatic_Background_Updates#Constant_to_Disable_All_Updates

**Reason:** In the alpha and beta versions of ClassicPress, the upgrade URLs have not been entirely replaced with the official ClassicPress release URL.

## Steps for the actual migration

Depends on whether the wp.org API calls **and** the WP upgrade URL can be replaced - the regular plugin and theme API calls seem to be adjustable via filter hooks. Also I don't know if the regular method is going to work if there is no API in place to answer these calls.

1. Hook into the filters for wp.org API and upgrade URL calls and change them to our own URLs.

2. Set a update core transient

3. Let the WP / CP upgrade routines do the rest

## Fallback option

If no wp.org API replacement is available, or these URLs cannot be changed sufficiently, a fallback option would be to use our own implementation of the upgrade / migration process. This process should require the following steps:

0. Backup database / wp_tables and files

1. Download latest release from the Github repository into `{WP_CONTENT_DIR}/upgrade`

2. Verify downloaded file via checksum

3. If download is wholesome, uncompress archive into the above mentioned `upgrade` directory

4. Set the `.maintenance` file in the WP root directory - also see: https://codex.wordpress.org/Function_Reference/wp_maintenance - this possibly might also be called via a background / AJAX process, because .maintenance might lead to unforseen behaviour (eg. WP being stuck in Maintenance Mode during internal calls)

5. Either overwrite all updates files with our own, using a pre-supplied list (eg. in the release archive) - or move the new `wp-includes` and `wp-admin` directory in place, overwriting all pre-existing files. A third option would be to copy the new `wp-includes` and `wp-admin` directory to the root, but with different names, eg. `_wp-includes` and `_wp-admin`, rename the original ones to eg. `.wp-includes` and `.wp-admin`, and then rename the before-copied ones to the correct names, ie. `wp-includes` and `wp-admin` (of corpse this also counts for the WP root directory).

6. Test whether all files / directories have been updated / replaced correctly.

7. After successful installation, remove the `.maintenance` from the WP (now CP) root directory

## Steps to do after migration

1. If some part of the migration process failed, have a simple "return to original installation" script sitting in place, that comes up automatically after the first reload, but is also given as an URL to the user during the migration process.

**Comment by nylen** [comment]
I'd add one thing to this list:  a prompt for site owners to **take a full backup** of the site first.  If I were implementing this, I would not show the UI for the actual migration until the user has confirmed that they've taken a fresh backup.

I'm leaving some notes on other points below.  Other than that, sounds good so far, and thanks for the investigation so far!

> ### 2. Enable SSL

I'm not sure how much we should push this.  It's a general best practice, but it shouldn't be a requirement to use ClassicPress.  For example, I do not have SSL enabled on my local dev site, but this is not a problem.

> ### 3. Disable automatic updates
> **Reason**: In the alpha and beta versions of ClassicPress, the upgrade URLs have not been entirely replaced with the official ClassicPress release URL.

We need to go ahead and replace these URLs (or otherwise disable automatic updates in the ClassicPress code) as soon as possible.  After that, I don't think this step will be needed.

> Depends on whether the wp.org API calls **and** the WP upgrade URL can be replaced

This will be possible one way or another.  The last resort option, if there is not a cleaner way, is to hook into [`pre_http_request`](https://developer.wordpress.org/reference/hooks/pre_http_request/) and override the response for the upgrade API.

> Also I don't know if the regular method is going to work if there is no API in place to answer these calls.

Yep, we need to set this up very soon.

> a fallback option would be to use our own implementation of the upgrade / migration process

As above, we shouldn't need to do this (using the `pre_http_request` hook as a last resort option).

> If some part of the migration process failed, have a simple "return to original installation" script sitting in place

This sounds complex and error-prone (if we don't know why the upgrade failed, I wouldn't expect a script to be able to fix it either).  Have you thought about what this script might do / how it might work?  I think this task is a bonus rather than mandatory for v1, and I'd prefer strongly encouraging the user to take a backup before doing the migration.

**Comment by nylen** [comment]
So, as far as I know, we have 3 immediate action items in order to unblock coding and testing work for the migration plugin.

- Disable WP automatic updates in the ClassicPress code.  (These should be switched over to using ClassicPress, but we'll probably just want to turn it off for now.)
- Build an alpha zip of ClassicPress and release it on GitHub.
- Get the relevant bits of api.classicpress.net working.  (Which endpoints specifically do we need, and what do they return?)

Anything else?

**Comment by nylen** [comment]
Closing, as this is mostly all implemented now:

![2018-10-22t15 12 49-05 00](https://user-images.githubusercontent.com/227022/47320911-7b3db180-d618-11e8-9848-a8a1fa81db91.png)

The only thing left is locale handling, but we'll get to that when we have locale-specific builds.

**Comment by nylen** [comment]
Locale handling: #18
