### ISSUE TITLE
Update detected after custom migration

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Migration-Plugin#62]
From https://forums.classicpress.net/t/classicpress-1-1-0-rc1-release-notes/1582/3:

![migration](https://user-images.githubusercontent.com/227022/65367172-f2126e80-dc1c-11e9-9bc1-f5b5e61e018f.jpg)

Looks like there is some updater state that we need to clear after doing a custom/advanced migration.

Edit to add:

- This happens sometimes but not every time in my testing
- If you go to “Dashboard > Updates” and click “Check Again”, then this should clear itself.

**Comment by bahiirwa** [comment]
This happens in all my migrations. Always have that custom_migration version notice.

**Comment by johnalarcon** [comment]
I think what's going on here is that the message is actually showing 2 different things. The first part is saying there's a new version of the migration plugin (which actually leads to a [404](https://github.com/ClassicPress/ClassicPress-Network/issues/61#issuecomment-553612624), btw), so, that's definitely broken.

The other part of the message is telling you that there's a _core_ update available (because you just downgraded, there's now a core update available), ...and when you visit the updates page, there it is...instead of the migration plugin update you were expecting because of the messaging. About the second half of the message, it should be clearer about what you are updating.

Just a guess here... are these status messages being concatenated, rather than added individually.

**Comment by nylen** [comment]
Belated reply to @johnalarcon's comment above, now that this is fixed:

There is nothing in the migration plugin that would show an update notice for the plugin itself.

This happened because the migration plugin needs to trick the core update process into updating, and to do that, it needs to set the version number that will be installed. Since we don't know the version number of the zip file the user enters (it could be anything), we just use the string `_custom_migration`.

This data was "sticking around" after migration, so the core update system thought it was still time to install a new version of CP/WP called `_custom_migration`. The fix is to remove this stale update data after a migration is done.
